### ISSUE TITLE
do agent failed to send metrics: circuit breaker is open

### ISSUE THREAD

**Issue by mirkhamidov** [digitalocean/do-agent#114]
## Describe the problem

we got errors

![2019-03-23_02-19-10](https://user-images.githubusercontent.com/2736223/54857754-11821a80-4d12-11e9-8398-3a31bdb10c99.png)

If restart droplet it works some time, and then starts again to show an error

in syslog
```
DigitalOceanAgent[1419]: ERROR: 2019/03/22 23:15:12 /gopath/src/github.com/digitalocean/do-agent/cmd/do-agent/run.go:47: failed to send metrics: circuit breaker is open; deliberately failing due to exponential backoff
```

## Steps to reproduce

dont know

## Expected behavior

no error shown

## System Information
Distribution and version: Ubuntu 16.04.6 LTS (GNU/Linux 4.4.0-143-generic x86_64)

### do-agent information:
Paste the entire output

`/opt/digitalocean/bin/do-agent --version`:

```
$ /opt/digitalocean/bin/do-agent --version

do-agent (DigitalOcean Agent)

Version:     2.0.2
Revision:    08dc07b
Build Date:  Thu Mar  7 19:07:30 UTC 2019
Go Version:  go1.11.5
Website:     https://github.com/digitalocean/do-agent

Copyright (c) 2019 DigitalOcean, Inc. All rights reserved.

This work is licensed under the terms of the Apache 2.0 license.
For a copy, see <https://www.apache.org/licenses/LICENSE-2.0.html>.
```

_Ubuntu, Debian_

`apt-cache policy do-agent`:
```
$ apt-cache policy do-agent
do-agent:
  Installed: 2.0.2
  Candidate: 2.0.2
  Version table:
 *** 2.0.2 100
        100 /var/lib/dpkg/status
     0.5.1 500
        500 https://repos.sonar.digitalocean.com/apt main/main amd64 Packages
```

**Comment by BeingTomGreen** [comment]
We're seeing the same. Have also lost historic stats as of today, and the metrics are intermittently not displaying in the dashboard.

```
$ /opt/digitalocean/bin/do-agent --version

do-agent (DigitalOcean Agent)

Version:     2.0.2
Revision:    08dc07b
Build Date:  Thu Mar  7 19:07:30 UTC 2019
Go Version:  go1.11.5
...
```

**Comment by isjg** [comment]
Looking at the code (search for: ``ErrCircuitBreaker``) it seems that the error _circuit breaker is open; deliberately failing due to exponential backoff_ is a kind of warning rather than an error. It happens when the ```do-agent``` cancels an attempt to send the data due to some problems when accessing the metrics service. Still it will try again and again each time making the waiting period statistically longer to avoid overload of metrics service by untempered retries (something like _exponential backoff_).

``do-agnet`` sends metrics to ``<region>.sonar.digitalocean.com``, where ``<region>`` names are the same as in droplets parameters: ``ams3``, ``fra1``, etc. In my case (ubuntu)  ``do-agent`` was installed as expected, ``systemctl status do-agent`` showed it works ok, however ``ping fra1.sonar.digitalocean.com`` failed pointing me to a wrong configuration of the firewall blocking an access to the sonar service. HTH.

**Comment by blockloop** [comment]
Could you provide some error logs from do-agent (if there are any)?

```journalctl -e -x -u do-agent | grep ERROR```

**Comment by blockloop** [comment]
Sorry to cut this conversation short, but the issues you are describing potentially involve
much more than do-agent. if you're still having issues with the agent, please contact our
support team at https://cloudsupport.digitalocean.com/s/.

I have [updated the issue template](https://github.com/digitalocean/do-agent/commit/0a73cd792b7cc445e1ab2f5053046d645151e44f) to be more specific about the kinds of issues that should be
reported on github. Sorry for the confusion :)

**Comment by pmalhaire** [comment]
I faced the same issue

**Comment by rootlinux2** [comment]
I'm facing the same ISSUE
