### ISSUE TITLE
Upgrade from the Legacy Metrics Agent to the Current Agent

### ISSUE THREAD

**Issue by monoflash** [digitalocean/do-agent#201]
```
# curl -sSL https://repos.insights.digitalocean.com/install.sh | sudo bash
Cleaning up old sources...OK
Verifying machine compatability...OK
Verifying compatability with script...
This script does not support the OS/Distribution on this machine.
If you feel that this is an error contact support@digitalocean.com
or create an issue at https://github.com/digitalocean/do-agent/issues/new.
```

Please post links to rpm packages, you do not know how to make scripts. Once again I have to open the script and collect the link to download and install the package with my hands.
I hope that I was heard.
Thanks.

**Comment by blockloop** [comment]
Please don't post any insulting comments. If you feel like there is an issue with the script please fill out the issue template appropriately so we know what we're supposed to help you with.

The script is designed to ignore unsupported distros. One of the questions in the issue template asks which distro you're running. If your distro is listed [under the supported distros list](https://github.com/digitalocean/do-agent#overview) please let us know and we can fix it. Otherwise, the script did exactly what it was written to do.

**Comment by monoflash** [comment]
I did not insult anyone, not even a thought about it. Not being able to do anything is an insult only for non-professionals.

If you are not professionals, then I apologize for having offended your incompetence.

The question is closed.
Thanks.

**Comment by thorfour** [comment]
You might find this link helpful

https://youtu.be/lUZ1ytMrkvA
