### ISSUE TITLE
FR: CoreOS

### ISSUE THREAD

**Issue by lucasyvas** [digitalocean/do-agent#32]
The announcement noticeably omitted CoreOS. Is there a technical reason for this? I'm not savvy in all the reasons why this might be. Perhaps the most popular were targeted first?

**Comment by TrurlMcByte** [comment]
I'm using own build with, created via ```CGO_ENABLED=0 make```

**Comment by utlemming** [comment]
There is no particular reason why the Agent is not supported on Core-OS other than the integration story. For example:
1. How do we automatically install the Agent?
2. Integration with SystemD to auto-start the Agent? 
3. What about upgrades?

I spent a fair amount of time scoping the work to make the agent magically work on CoreOS. I am a big fan of doing things the way the distro _intends_ and to make it work on CoreOS means that we need to get support for the agent via the OEM channel. Otherwise an upgrade will nullify the agent and that is not exactly desirable :/

In the mean time, I would suggest that you make the request via https://digitalocean.uservoice.com for CoreOS support.

I'll take a look at making things a bit easier for our CoreOS users, but proper support is going to take a bit.

**Comment by TrurlMcByte** [comment]
I'm using my own way via fleetd with custom deploy. But it's mean "manual" build in any case (run one script if repository have changes).

**Comment by sevoma** [comment]
Fleetd and Docker Swarm service deployment options would be great. 

@TrurlMcByte, could you share your fleetd config?

For anyone looking for other options, Datadog's free tier supports up to 5 hosts and supports etcd config and docker containers: https://www.datadoghq.com/blog/monitor-coreos-scale-datadog/
You can also run dd as a Docker Swarm service. If you go the dd route, you can get container metrics too :)

**Comment by danackerson** [comment]
as easy as:
```
docker run -d --name dd-agent \
   -v /var/run/docker.sock:/var/run/docker.sock:ro \
   -v /proc/:/host/proc/:ro \
   -v /sys/fs/cgroup/:/host/sys/fs/cgroup:ro \
   -e DD_API_KEY=$DataDog_API_KEY datadog/agent:latest
```

**Comment by malkir** [comment]
+1 this

@utlemming would it be possible to leverage CoreOS's strengths, and have the user manage monitoring themselves by creating a do-agent service to add to their swarm cluster? Seems like a middle ground that could be achieved.
